{"uuid": "6cc767c7-5d4e-42f2-8eb8-b6824dab145f", "children": ["60221fbd-a09e-4787-9086-8be53bb92446"], "befores": [{"name": "xunit_setup_class_fixture_TestPjj", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: A new session could not be created. Details: The desiredCapabilities object was not valid for the following reason(s): 'deviceName' must be of type string\n\n", "trace": "  File \"d:\\python37\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"d:\\python37\\lib\\site-packages\\_pytest\\python.py\", line 811, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"d:\\python37\\lib\\site-packages\\_pytest\\python.py\", line 739, in _call_with_optional_argument\n    func(arg)\n  File \"E:\\workspaces\\SeleniumPython\\Script\\test_pjj.py\", line 20, in setup_class\n    self.driver = GetDriver.init_driver()\n  File \"E:\\workspaces\\SeleniumPython\\Basic\\Get_Driver.py\", line 28, in init_driver\n    cls.driver = webdriver.Remote(\"http://127.0.0.1:4723/wd/hub\", desired_caps)\n  File \"d:\\python37\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 157, in __init__\n    AppiumConnection(command_executor, keep_alive=keep_alive), desired_capabilities, browser_profile, proxy\n  File \"d:\\python37\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"d:\\python37\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 226, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, parameters)\n  File \"d:\\python37\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"d:\\python37\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1635992120165, "stop": 1635992120343}], "start": 1635992120165, "stop": 1635992120475}